import type { Metadata } from "next";
import "./globals.css";
import {ThemeProvider} from "@/components/shared/theme/theme-provider";
import {ThemeToggle} from "@/components/shared/theme/theme-toggle";
import {Header} from "@/components/shared/header/header";
import {Toaster} from "@/components/ui/sonner";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className={`antialiased`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <Toaster />
            <div className={`px-8`}>
                <Header />
                {children}
            </div>
        </ThemeProvider>
        </body>
        </html>
    );
}
