import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/shared/theme/theme-provider";
import { Header } from "@/components/shared/header/header";
import { Toaster } from "@/components/ui/sonner";
import { QueryProvider } from "@/components/providers/query-provider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className="antialiased">
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <QueryProvider>
                <Toaster richColors position="bottom-right" />
                <div className=" pb-8">
                    <Header />
                    {children}
                </div>
            </QueryProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
